int _putchar(char a);
void reset_to_98(int *a);
void swap_int(int *a, int *b);
int _strlen(char *a);
void _puts(char *a);
void print_rev(char *a);
void rev_string(char *g);
void puts2(char *a);
void puts_half(char *a);
void print_array(int *a, int b);
char *_strcpy(char *a, char *b);
int _atoi(char *a);
